# Generated by Django 2.2.4 on 2019-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbascrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbanews',
            name='image_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
