# Generated by Django 2.2.4 on 2019-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbascrap', '0002_nbanews_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
