# Generated by Django 2.2.4 on 2019-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbascrap', '0003_auto_20190808_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbanews',
            name='uid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
