# Generated by Django 2.2.4 on 2019-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbascrap', '0004_nbanews_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
