# Generated by Django 2.1.2 on 2018-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('img_url', models.TextField()),
                ('time', models.DateTimeField()),
                ('news_text', models.TextField()),
            ],
            options={
                'db_table': 'news_table',
            },
        ),
    ]
