# Generated by Django 3.0.4 on 2020-03-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBANewsPage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='標題')),
                ('href', models.CharField(max_length=256, verbose_name='連結')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'News',
            },
        ),
    ]
