# Generated by Django 2.1.1 on 2019-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
