# Generated by Django 2.1.1 on 2019-04-18 09:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190418_1505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('news_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
