# Generated by Django 2.1.1 on 2019-04-18 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190418_1727'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
