# Generated by Django 2.1.1 on 2019-04-20 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='update_time',
        ),
        migrations.AddField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
