# Generated by Django 2.0.7 on 2019-02-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
