# Generated by Django 2.1.7 on 2020-03-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('post_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
