# Generated by Django 2.1.7 on 2020-03-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='subtitle',
        ),
    ]
