# Generated by Django 2.1.7 on 2020-03-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_remove_news_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='post_url',
            new_name='news_url',
        ),
    ]
