# Generated by Django 2.2.7 on 2019-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('link_path', models.CharField(max_length=255)),
                ('src', models.CharField(default='', max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
