# Generated by Django 2.2.2 on 2019-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topnews', '0002_news_crawl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='crawl_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
