# Generated by Django 2.2 on 2019-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbanewsinfocus',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
