# Generated by Django 2.1.3 on 2018-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'topNews',
            },
        ),
    ]
