# Generated by Django 2.1.3 on 2018-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseNbaUdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='pageUrl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='postId',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='topnews',
            table='TopNews',
        ),
    ]
