# Generated by Django 2.1.3 on 2018-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseNbaUdn', '0002_auto_20181106_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topnews',
            name='text',
        ),
        migrations.AlterField(
            model_name='topnews',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='pageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='postId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='title',
            field=models.TextField(),
        ),
    ]
