# Generated by Django 2.1.3 on 2018-11-06 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parseNbaUdn', '0003_auto_20181106_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topnews',
            options={'ordering': ['-adding_time']},
        ),
        migrations.AddField(
            model_name='topnews',
            name='adding_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='adding_time'),
        ),
    ]
