# Generated by Django 2.1.3 on 2018-11-07 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parseNbaUdn', '0006_auto_20181106_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topnews',
            options={'ordering': ['-addingTime']},
        ),
        migrations.RemoveField(
            model_name='topnews',
            name='adding_time',
        ),
        migrations.AddField(
            model_name='topnews',
            name='addingTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='addingTime'),
        ),
    ]
