# Generated by Django 2.2.5 on 2019-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('date', models.DateTimeField()),
                ('source', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'nba_news',
            },
        ),
    ]
