# Generated by Django 3.0.1 on 2019-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191228_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
