# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('news_id', models.AutoField(db_column='news_id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('text', models.TextField(db_column='text')),
                ('picture', models.TextField(db_column='picture')),
                ('potime', models.DateTimeField(db_column='potime')),
            ],
            options={
                'db_table': 'Catch',
            },
        ),
    ]
