# Generated by Django 2.2.2 on 2019-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內文')),
                ('created_at', models.DateTimeField(verbose_name='時間')),
                ('scrapped_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取時間')),
            ],
            options={
                'verbose_name': '新聞',
                'verbose_name_plural': '新聞列表',
            },
        ),
    ]
