# Generated by Django 2.2.2 on 2019-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, verbose_name='連結'),
        ),
    ]
