# Generated by Django 2.2.4 on 2019-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imgUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='payload',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
