# Generated by Django 2.1.2 on 2018-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181101_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.TextField(default='http://'),
        ),
    ]
