# Generated by Django 2.1.2 on 2018-10-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181020_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='id',
            new_name='uuid',
        ),
    ]
