# Generated by Django 2.2.4 on 2019-08-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='fb_like',
            new_name='fbLike',
        ),
    ]
