# Generated by Django 2.2.4 on 2019-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190808_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='fbLike',
            field=models.CharField(default='', max_length=15),
        ),
    ]
