# Generated by Django 2.2.4 on 2019-08-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190808_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='imgUrl',
            field=models.URLField(default=''),
        ),
    ]
