# Generated by Django 2.2.3 on 2019-08-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='newsid')),
                ('title', models.TextField(max_length=66, verbose_name='title')),
                ('introduction', models.TextField(verbose_name='introduction')),
            ],
            options={
                'verbose_name': 'NBA新聞清單',
                'verbose_name_plural': 'NBA 新聞清單',
                'db_table': 'news.News',
            },
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_id', serialize=False, to='news.NewsModel', verbose_name='news_id')),
                ('content_title', models.TextField(max_length=66, verbose_name='title')),
                ('content_url', models.TextField(max_length=180, verbose_name='url')),
                ('content_text', models.TextField(verbose_name='text')),
                ('news_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'NBA新聞內文',
                'verbose_name_plural': 'NBA 新聞內文',
                'db_table': 'news.content',
            },
        ),
    ]
