# Generated by Django 2.2.3 on 2019-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='introduction',
            field=models.CharField(max_length=188, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=66, verbose_name='title'),
        ),
    ]
