# Generated by Django 2.2.3 on 2019-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190828_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='introduction',
            field=models.TextField(verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.TextField(max_length=66, verbose_name='title'),
        ),
    ]
