# Generated by Django 2.1 on 2019-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
