# Generated by Django 2.1 on 2019-08-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotnews',
            name='news_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
