# Generated by Django 3.0.4 on 2020-03-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
