# Generated by Django 3.0.4 on 2020-03-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_remove_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='web_link',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
