# Generated by Django 2.2 on 2019-06-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190605_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='guesttemporaryinfo',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='7d342844', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
