# Generated by Django 2.2 on 2019-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190610_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBauser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('eda_role', models.CharField(blank=True, max_length=512, null=True)),
                ('lej_api_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('reverse_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('password_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('tb_api_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('ms_api_token', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'core_bauser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomerInfosBak20190429',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='788c062a', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
