# Generated by Django 2.2 on 2019-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190621_0856'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='transaction',
    #         name='ecpay_merchant_trade_no',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='transaction',
    #         name='newebpay_merchant_trade_no',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='transaction',
    #         name='other_amount',
    #         field=models.FloatField(default=0),
    #     ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='47e7e956', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
