# Generated by Django 2.2 on 2019-06-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190621_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='a60d89ff', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
