# Generated by Django 2.2 on 2019-06-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190624_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='399b3f64', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
