# Generated by Django 2.2 on 2019-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20190625_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingcartPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_no', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'shoppingcart_premium',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='df9f7276', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
