# Generated by Django 2.2 on 2019-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20190626_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartpremium',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='a4761124', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
