# Generated by Django 2.2 on 2019-06-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20190626_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartpremium',
            old_name='customer_id',
            new_name='service_customer_id',
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='028e6641', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
