# Generated by Django 2.2 on 2019-06-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20190626_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartpremium',
            name='lej_customer_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='01b56ebd', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
