# Generated by Django 2.2 on 2019-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20190627_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartpremium',
            name='device_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='318077ad', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
