# Generated by Django 2.2 on 2019-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20190627_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartpremium',
            name='price_prefix',
            field=models.CharField(default='TWD', max_length=50),
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='f595a0ee', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
