# Generated by Django 2.2 on 2019-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20190627_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='58ba2293', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingcartpremium',
            name='device_type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
