# Generated by Django 2.2 on 2019-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20190703_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='c2cb1301', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
