# Generated by Django 2.2 on 2019-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20190703_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='b4cb57ea', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
