# Generated by Django 2.2 on 2019-07-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20190703_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='guesttemporaryinfo',
            name='id',
            field=models.CharField(default='aaaaaa', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
