# Generated by Django 2.2 on 2019-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20190716_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='line_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(default=0),
        ),
    ]
