# Generated by Django 2.2 on 2019-07-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20190716_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
