# Generated by Django 2.2 on 2019-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_auto_20190716_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lej_customer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('service_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('newebpay_authorized_token', models.CharField(blank=True, max_length=255, null=True)),
                ('newebpay_authorized_token_life', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_tokens',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
    ]
