# Generated by Django 2.2.2 on 2019-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('url_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='新聞ID')),
                ('url_detail', models.URLField(blank=True, null=True, verbose_name='詳細頁面網址')),
                ('image', models.URLField(blank=True, null=True, verbose_name='照片')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新時間')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='標題')),
                ('statement', models.CharField(blank=True, max_length=50, null=True, verbose_name='簡短敘述')),
            ],
        ),
    ]
