# Generated by Django 2.2.2 on 2019-06-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='發表時間'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_content',
            field=models.TextField(blank=True, null=True, verbose_name='詳細內文'),
        ),
    ]
