# Generated by Django 2.2.3 on 2019-07-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='abstract',
        ),
    ]
