# Generated by Django 2.2.3 on 2019-07-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20190729_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['id'], 'verbose_name': '焦點文章', 'verbose_name_plural': '焦點文章'},
        ),
    ]
