# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('crawled_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('image_url', models.TextField()),
                ('published_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
                'ordering': ('crawled_time',),
            },
        ),
    ]
