# Generated by Django 2.1.2 on 2018-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newscatch',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('cotent', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
