# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(default='hehehe', max_length=1000),
            preserve_default=False,
        ),
    ]
