# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='article',
            new_name='fulltext',
        ),
    ]
