# Generated by Django 2.2.4 on 2019-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20190826_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
