# Generated by Django 2.2.6 on 2019-10-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spotnews',
            table='SpotNews',
        ),
    ]
