# Generated by Django 2.2.6 on 2019-10-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191029_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotnews',
            name='newsimg',
            field=models.TextField(default=''),
        ),
    ]
