# Generated by Django 2.2.6 on 2019-10-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spotnews_newsimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotnews',
            name='newsimg',
            field=models.TextField(default='NoImg'),
        ),
    ]
