# Generated by Django 2.2.6 on 2019-10-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191030_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotnews',
            name='newsimg',
            field=models.TextField(blank=True),
        ),
    ]
