# Generated by Django 2.1 on 2018-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300)),
                ('headline', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'top_news',
            },
        ),
    ]
