# Generated by Django 2.1 on 2018-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_topnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='body',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='link',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
