# Generated by Django 2.1 on 2018-08-04 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='hbody',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
