# Generated by Django 2.2.1 on 2019-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(db_column='news_id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('content', models.TextField(db_column='content')),
                ('figure_url', models.TextField(db_column='figure_url')),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
