# Generated by Django 2.2.1 on 2019-05-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='News_model',
        ),
    ]
