# Generated by Django 2.2.1 on 2019-05-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_django', '0002_auto_20190523_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_model',
            name='date',
        ),
        migrations.AddField(
            model_name='news_model',
            name='crawled_time',
            field=models.TextField(db_column='crawled_time', default='some time', max_length=50),
        ),
        migrations.AddField(
            model_name='news_model',
            name='published_time',
            field=models.TextField(db_column='published_time', default='some time', max_length=50),
        ),
        migrations.AddField(
            model_name='news_model',
            name='url',
            field=models.TextField(db_column='url', default='some url', max_length=100),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='content',
            field=models.TextField(db_column='content', default='some content', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='figure_url',
            field=models.TextField(db_column='figure_url', default='some url', max_length=100),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='title',
            field=models.TextField(db_column='title', default='some title', max_length=100),
        ),
    ]
