# Generated by Django 2.2.1 on 2019-05-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_django', '0003_auto_20190523_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='content',
            field=models.TextField(db_column='content', default='some content', max_length=5000),
        ),
    ]
