# Generated by Django 2.2.5 on 2019-09-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndex',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nbanewsreader.NewsIndex')),
            ],
        ),
    ]
