# Generated by Django 2.0.6 on 2020-03-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='udn',
            table='udn',
        ),
    ]
