# Generated by Django 2.2.5 on 2019-10-17 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAframework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=120)),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('image_caption', models.CharField(max_length=120)),
                ('video_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('publish_date',),
            },
        ),
    ]
