# Generated by Django 2.2.2 on 2019-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0002_auto_20190609_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.CharField(max_length=1024),
        ),
    ]
