# Generated by Django 2.2.2 on 2019-06-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0003_auto_20190609_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='article',
        ),
    ]
