# Generated by Django 2.2.2 on 2019-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0004_remove_news_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(default=''),
        ),
    ]
