# Generated by Django 2.2.2 on 2019-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0005_news_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
