# Generated by Django 2.0.3 on 2018-09-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_time', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('img_src', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
