# Generated by Django 3.0.3 on 2020-03-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaspotnews',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
