# Generated by Django 3.0.3 on 2020-03-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200303_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaspotnews',
            name='news_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nbaspotnews',
            name='photo_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nbaspotnews',
            name='report_source',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nbaspotnews',
            name='report_url',
            field=models.TextField(default=''),
        ),
    ]
