# Generated by Django 3.0.3 on 2020-03-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_nbaspotnews_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNewsTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_news_title', models.TextField(default='')),
            ],
        ),
    ]
