# Generated by Django 2.0.5 on 2018-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
