# Generated by Django 2.0.3 on 2018-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbanewsmodel',
            name='feature_pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
