# Generated by Django 3.0.1 on 2019-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(default='no image provide', max_length=250),
        ),
    ]
