# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
