# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscraper', '0002_auto_20171013_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pyscraper.Headline'),
        ),
    ]
