# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscraper', '0003_auto_20171015_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline_text',
            field=models.CharField(max_length=255),
        ),
    ]
