version: "3"
services:
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        restart: always

    myproject-dev:
        build: . 
        image: superchen/nice_to_meet_you:latest
        command: python manage.py runserver 0.0.0.0:8000
        restart: always
        ports:
            - "8000:8000"

    myproject:
        build: . 
        image: superchen/nice_to_meet_you:latest
        command: gunicorn myproject.wsgi:application --bind unix:/socket/gunicorn.sock
        restart: always
        volumes:
            - unix_socket:/socket
            - static:/www/static

    myproject-nginx:
        image: nginx:latest
        volumes:
            - unix_socket:/socket
            - static:/static
            - ./static/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - myproject

    myproject-celery:
        build: . 
        image: superchen/nice_to_meet_you:latest
        command: celery -A myproject --beat worker -l debug
        restart: always

volumes:
    static:
    unix_socket:
