# Generated by Django 2.2.5 on 2019-09-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UdnNBANewsParser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NBANews',
        ),
    ]
