# Generated by Django 2.2.5 on 2019-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdnNBANewsParser', '0003_nbanews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
