# Generated by Django 2.2.5 on 2019-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdnNBANewsParser', '0005_auto_20190907_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='content',
            field=models.TextField(max_length=65535, verbose_name='content'),
        ),
    ]
