# Generated by Django 2.2.5 on 2019-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdnNBANewsParser', '0006_auto_20190908_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbanews',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
