# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('content', models.TextField(blank=True, max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
