# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-12 04:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(default='No Content')),
                ('link', models.TextField(default='https://nba.udn.com', validators=[django.core.validators.URLValidator()])),
                ('photo', models.TextField(default='https://nba.udn.com', validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
