# Generated by Django 2.1.5 on 2019-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.CharField(max_length=200, null=True)),
                ('newscontent', models.TextField(max_length=5000, null=True)),
                ('newsimg', models.TextField(max_length=200, null=True)),
                ('newstime', models.TextField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['-newstime'],
            },
        ),
    ]
