# Generated by Django 2.1.5 on 2019-01-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20190121_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_time']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newscontent',
            new_name='news_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newsimg',
            new_name='news_img',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newstime',
            new_name='news_time',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newstitle',
            new_name='news_title',
        ),
    ]
