# Generated by Django 2.1.5 on 2019-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20190121_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
