# Generated by Django 2.1.7 on 2019-03-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190306_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='datetime',
            new_name='uploadDatetime',
        ),
    ]
