# Generated by Django 2.2.6 on 2019-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'HotInfo',
            },
        ),
    ]
