# Generated by Django 3.0.4 on 2020-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanewspage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
