# Generated by Django 2.2.4 on 2019-08-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAHotNewsApp', '0002_auto_20190831_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbahotnews',
            name='NewsDetailUrl',
        ),
        migrations.AddField(
            model_name='nbahotnews',
            name='Author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbahotnews',
            name='NewsDetailContent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbahotnews',
            name='NewsDetailImgUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NBAHotNewsDetail',
        ),
    ]
