# Generated by Django 2.2.4 on 2019-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAHotNewsApp', '0003_auto_20190831_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbahotnews',
            name='Author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nbahotnews',
            name='NewsTitle',
            field=models.CharField(max_length=100),
        ),
    ]
