# Generated by Django 2.2.4 on 2019-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAHotNewsApp', '0004_auto_20190831_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbahotnews',
            name='ImgUrl',
        ),
        migrations.RemoveField(
            model_name='nbahotnews',
            name='NewsDetailImgUrl',
        ),
        migrations.AddField(
            model_name='nbahotnews',
            name='ImgFileName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
