# Generated by Django 2.2.4 on 2019-09-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAHotNewsApp', '0005_auto_20190901_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelName', models.CharField(max_length=100)),
            ],
        ),
    ]
