# Generated by Django 2.2.4 on 2019-09-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAHotNewsApp', '0006_websocketclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSocketClient',
        ),
    ]
