# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('date', models.DateField(verbose_name='date')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
