# Generated by Django 2.1.7 on 2019-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
