# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBANewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_caption', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
