# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0002_auto_20180731_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanewsmodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
