# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0003_auto_20180731_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbanewsmodel',
            name='available',
        ),
        migrations.AddField(
            model_name='nbanewsmodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nbanewsmodel',
            name='video_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
