# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0004_auto_20180731_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nbanewsmodel',
            options={'ordering': ('publish_date',)},
        ),
    ]
