# Generated by Django 3.0.4 on 2020-03-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CrawlerAt', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=100)),
                ('CreateAt', models.DateTimeField()),
                ('Content', models.CharField(max_length=1000)),
                ('Url', models.CharField(max_length=1000)),
            ],
        ),
    ]
