# Generated by Django 2.1.2 on 2018-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nbanews',
            name='created',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
