# Generated by Django 2.2.2 on 2019-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rel_date', models.DateTimeField(blank=True, null=True)),
                ('nba_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nba',
                'managed': False,
            },
        ),
    ]
