# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('outline', models.TextField()),
                ('url', models.URLField()),
                ('img_url', models.URLField()),
                ('content', models.TextField()),
                ('post_date', models.CharField(max_length=30)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
