# Generated by Django 2.1.5 on 2019-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
