# Generated by Django 2.2 on 2019-07-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0021_auto_20190703_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reated_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.Transaction')),
            ],
            options={
                'db_table': 'invoice_history',
                'managed': True,
            },
        ),
    ]
