# Generated by Django 2.2 on 2019-07-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicehistory',
            name='transaction',
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
