# Generated by Django 2.2 on 2019-07-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190703_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicehistory',
            old_name='reated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='merchant_order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='total_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
