# Generated by Django 2.0.7 on 2018-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, default='', max_length=250)),
                ('story_url', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('video_url', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('datetime', 'title')},
        ),
    ]
