# Generated by Django 2.0.4 on 2018-04-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180410_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('datetime',)},
        ),
    ]
