# Generated by Django 2.2.3 on 2019-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_time', models.CharField(max_length=15)),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('image_source', models.URLField(null=True)),
                ('video_source', models.URLField(null=True)),
            ],
        ),
    ]
