# Generated by Django 2.2.3 on 2019-07-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Nba',
        ),
    ]
