# Generated by Django 2.2.3 on 2019-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190721_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nba',
            name='date_time',
            field=models.CharField(max_length=16),
        ),
    ]
