# Generated by Django 2.2.3 on 2019-07-21 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190721_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='nba',
            name='article_url',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
