# Generated by Django 2.2.3 on 2019-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_nba_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nba',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
