# Generated by Django 2.1.1 on 2018-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=8)),
                ('post_title', models.CharField(max_length=30)),
                ('post_date', models.CharField(max_length=16)),
                ('post_url', models.TextField()),
                ('post_image_url', models.TextField()),
                ('post_content', models.TextField()),
            ],
        ),
    ]
