# Generated by Django 2.1.1 on 2018-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
