# Generated by Django 2.1.7 on 2019-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('top', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('photo_url', models.URLField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
