# Generated by Django 2.2.2 on 2019-06-20 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBANewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('publish_date',),
            },
        ),
    ]
