# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('reporter', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'nba',
            },
        ),
    ]
