# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsinfo',
            old_name='image_url',
            new_name='image',
        ),
    ]
