# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
