# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAsite', '0002_auto_20190718_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='link',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='reporter',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
