# Generated by Django 2.2.5 on 2019-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='新聞標題')),
                ('url', models.URLField(default='', verbose_name='新聞網址')),
            ],
        ),
    ]
