# Generated by Django 2.2.3 on 2019-07-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cr_nba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('author', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
