# Generated by Django 2.2.3 on 2019-07-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
    ]
