# Generated by Django 2.2.6 on 2019-10-05 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('udn_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topnews',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='topnews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='topnews',
            table='top_news_spider',
        ),
    ]
