# Generated by Django 2.2.6 on 2019-10-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn_news', '0002_auto_20191005_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
