# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBA_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('content', models.TextField(verbose_name='\u7c21\u8ff0')),
                ('time', models.TimeField(verbose_name='\u767c\u8868\u6642\u9593')),
            ],
        ),
    ]
