# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetNews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NBA_News',
            new_name='News',
        ),
    ]
