# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetNews', '0002_auto_20190117_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Serial',
            field=models.CharField(max_length=256, verbose_name='\u6d41\u6c34\u865f'),
        ),
        migrations.AlterField(
            model_name='news',
            name='group_id',
            field=models.CharField(max_length=256, verbose_name='\u7d44\u5e8f\u865f'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.CharField(max_length=256, verbose_name='\u5716\u7247\u7db2\u5740'),
        ),
    ]
