# Generated by Django 2.1.5 on 2019-01-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetNews', '0005_auto_20190118_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateField(verbose_name='發表時間'),
        ),
    ]
