# Generated by Django 2.1.5 on 2019-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetNews', '0007_auto_20190118_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.CharField(default='', max_length=256, verbose_name='新聞網址'),
        ),
    ]
