# Generated by Django 2.1.2 on 2018-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlinePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('post_title', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_content', models.TextField()),
                ('post_url', models.URLField()),
                ('img_url', models.URLField()),
            ],
            options={
                'db_table': 'headlinepost',
            },
        ),
    ]
