# Generated by Django 2.2.2 on 2019-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('image_url', models.CharField(max_length=100, verbose_name='圖片連結')),
                ('short_description', models.CharField(max_length=100, verbose_name='短文字敘述')),
                ('detail', models.TextField(max_length=1000, verbose_name='內文')),
            ],
        ),
    ]
