# Generated by Django 2.2.2 on 2019-08-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.News')),
                ('detail', models.TextField(max_length=1000, verbose_name='內文')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='detail',
        ),
    ]
