# Generated by Django 2.2.2 on 2019-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190817_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, verbose_name='內文'),
        ),
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
