# Generated by Django 2.0 on 2019-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190817_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(max_length=100, verbose_name='圖片連結'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=100, verbose_name='短文字敘述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=100, unique=True, verbose_name='標題'),
        ),
    ]
