# Generated by Django 2.1.7 on 2019-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_new_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.CharField(default='', max_length=128),
        ),
    ]
