# Generated by Django 2.1.7 on 2019-03-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190328_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
