# Generated by Django 2.1.2 on 2018-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBANews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
